package com.hotel.booking.core.exception;

import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

import lombok.Getter;

@Getter
public enum ErrorCode {
        UNCATEGORIZED_EXCEPTION(9999, "Uncategorized error", HttpStatus.INTERNAL_SERVER_ERROR),
        INVALID_KEY(1001, "Uncategorized error", HttpStatus.BAD_REQUEST),
        STAFF_USERNAME_EXISTED(1002, "Username is already taken", HttpStatus.BAD_REQUEST),
        STAFF_USERNAME_NOT_BLANK(1003, "Username must not be blank", HttpStatus.BAD_REQUEST),
        STAFF_USERNAME_MIN_LENGTH(1004, "Username must be at least 3 characters", HttpStatus.BAD_REQUEST),
        STAFF_PASSWORD_MIN_LENGTH(1005, "Password must be at least 8 characters", HttpStatus.BAD_REQUEST),
        UNAUTHENTICATED(1006, "Unauthenticated", HttpStatus.UNAUTHORIZED),
        UNAUTHORIZED(1007, "You do not have permission", HttpStatus.FORBIDDEN),
        STAFF_NOT_FOUND(1008, "Staff member not found", HttpStatus.NOT_FOUND),

        STAFF_PASSWORD_NOT_BLANK(9004, "Password must not be blank", HttpStatus.BAD_REQUEST),
        ROLE_NOT_FOUND(2001, "Role not found", HttpStatus.NOT_FOUND),
        ROLE_CODE_EXISTED(2002, "Role code already existed", HttpStatus.BAD_REQUEST),
        ROLE_NAME_NOT_BLANK(2003, "Role name must not be blank", HttpStatus.BAD_REQUEST),
        ROLE_NAME_MAX_LENGTH(2004, "Role name must not exceed 100 characters", HttpStatus.BAD_REQUEST),
        ROLE_CODE_NOT_BLANK(2005, "Role code must not be blank", HttpStatus.BAD_REQUEST),
        ROLE_CODE_MAX_LENGTH(2006, "Role code must not exceed 50 characters", HttpStatus.BAD_REQUEST),
        ROLE_STATUS_NOT_NULL(2007, "Role status must not be null", HttpStatus.BAD_REQUEST),
        PERMISSION_NOT_FOUND(2008, "Permission not found", HttpStatus.NOT_FOUND),
        PERMISSION_ALREADY_EXISTS(2009, "Permission already exists", HttpStatus.BAD_REQUEST),
        PERMISSION_ACTION_NOT_BLANK(2010, "Permission action must not be blank", HttpStatus.BAD_REQUEST),
        PERMISSION_RESOURCE_NOT_BLANK(2011, "Permission resource must not be blank", HttpStatus.BAD_REQUEST),
        PERMISSION_STATUS_NOT_NULL(2012, "Permission status must not be null", HttpStatus.BAD_REQUEST),
        ROLE_PERMISSION_IDS_NOT_NULL(2013, "Permission IDs list for role assignment must not be null",
                        HttpStatus.BAD_REQUEST),
        GUEST_NOT_FOUND(3001, "Guest not found", HttpStatus.NOT_FOUND),
        GUEST_PHONE_EXISTED(3002, "Guest phone number already existed", HttpStatus.BAD_REQUEST),
        GUEST_PHONE_NOT_BLANK(3003, "Guest phone must not be blank", HttpStatus.BAD_REQUEST),
        HOTEL_NOT_FOUND(4001, "Hotel not found", HttpStatus.NOT_FOUND),
        HOTEL_NAME_EXISTED(4002, "Hotel name already existed", HttpStatus.BAD_REQUEST),
        HOTEL_NAME_NOT_BLANK(4003, "Hotel name must not be blank", HttpStatus.BAD_REQUEST),
        HOTEL_ADDRESS_NOT_BLANK(4004, "Hotel address must not be blank", HttpStatus.BAD_REQUEST),
        HOTEL_CHECKIN_TIME_NOT_NULL(4005, "Hotel check-in time must not be null", HttpStatus.BAD_REQUEST),
        HOTEL_CHECKOUT_TIME_NOT_NULL(4006, "Hotel check-out time must not be null", HttpStatus.BAD_REQUEST),
        HOTEL_SERVICE_FEE_NOT_NULL(4007, "Hotel service fee percent must not be null", HttpStatus.BAD_REQUEST),
        HOTEL_SERVICE_FEE_MIN(4008, "Hotel service fee percent must be at least 0.0", HttpStatus.BAD_REQUEST),
        HOTEL_SERVICE_FEE_MAX(4009, "Hotel service fee percent must not exceed 100.0", HttpStatus.BAD_REQUEST),
        ROOM_TYPE_NOT_FOUND(5001, "Room type not found", HttpStatus.NOT_FOUND),
        ROOM_TYPE_CODE_EXISTED(5002, "Room type code already existed", HttpStatus.BAD_REQUEST),
        ROOM_TYPE_CODE_NOT_BLANK(5003, "Room type code must not be blank", HttpStatus.BAD_REQUEST),
        ROOM_TYPE_NAME_NOT_BLANK(5004, "Room type name must not be blank", HttpStatus.BAD_REQUEST),
        ROOM_TYPE_STATUS_NOT_NULL(5005, "Room type status must not be null", HttpStatus.BAD_REQUEST),
        ROOM_TYPE_NAME_EXISTED(5006, "Room type name already existed", HttpStatus.BAD_REQUEST),
        ROOM_BED_NOT_FOUND(6001, "Room bed not found", HttpStatus.NOT_FOUND),
        ROOM_BED_NAME_EXISTED(6002, "Room bed name already existed", HttpStatus.BAD_REQUEST),
        ROOM_BED_NAME_NOT_BLANK(6003, "Room bed name must not be blank", HttpStatus.BAD_REQUEST),
        ROOM_BED_NAME_MAX_LENGTH(6004, "Room bed name must not exceed 100 characters", HttpStatus.BAD_REQUEST),
        ROOM_BED_SIZE_MAX_LENGTH(6005, "Room bed size must not exceed 50 characters", HttpStatus.BAD_REQUEST),
        ROOM_FEATURE_NOT_FOUND(7001, "Room feature not found", HttpStatus.NOT_FOUND),
        ROOM_FEATURE_CODE_EXISTED(7002, "Room feature code already existed", HttpStatus.BAD_REQUEST),
        ROOM_FEATURE_CODE_NOT_BLANK(7003, "Room feature code must not be blank", HttpStatus.BAD_REQUEST),
        ROOM_FEATURE_NAME_NOT_BLANK(7004, "Room feature name must not be blank", HttpStatus.BAD_REQUEST),
        ROOM_FEATURE_CODE_MAX_LENGTH(7005, "Room feature code must not exceed 50 characters", HttpStatus.BAD_REQUEST),
        ROOM_FEATURE_NAME_MAX_LENGTH(7006, "Room feature name must not exceed 150 characters", HttpStatus.BAD_REQUEST),
        ROOM_FEATURE_CATEGORY_MAX_LENGTH(7007, "Room feature category must not exceed 50 characters",
                        HttpStatus.BAD_REQUEST),
        ROOM_FEATURE_NAME_EXISTED(7008, "Room feature name already existed", HttpStatus.BAD_REQUEST),

        CATALOG_ITEM_NOT_FOUND(5101, "Catalog item not found", HttpStatus.NOT_FOUND),
        CATALOG_ITEM_HOTEL_ID_NOT_NULL(5102, "Catalog item hotel ID must not be null", HttpStatus.BAD_REQUEST),
        CATALOG_ITEM_NAME_NOT_BLANK(5103, "Catalog item name must not be blank", HttpStatus.BAD_REQUEST),
        CATALOG_ITEM_TYPE_NOT_NULL(5104, "Catalog item type must not be null", HttpStatus.BAD_REQUEST),
        CATALOG_ITEM_VAT_RULE_ID_NOT_NULL(5105, "Catalog item VAT rule ID must not be null", HttpStatus.BAD_REQUEST),
        CATALOG_ITEM_BASE_PRICE_NOT_NULL(5106, "Catalog item base price must not be null", HttpStatus.BAD_REQUEST),
        CATALOG_ITEM_BASE_PRICE_MIN(5107, "Catalog item base price must be at least 0.0", HttpStatus.BAD_REQUEST),
        CATALOG_ITEM_STATUS_NOT_NULL(5108, "Catalog item status must not be null", HttpStatus.BAD_REQUEST),

        HOTEL_ROOM_TYPE_NOT_FOUND(5201, "Hotel room type mapping not found", HttpStatus.NOT_FOUND),
        HOTEL_ROOM_TYPE_ALREADY_EXISTS(5202, "This hotel already has this room type configured",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_INVALID_ADULTS_CAPACITY(5203, "Standard adults cannot exceed max adults",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_INVALID_CHILDREN_CAPACITY(5204, "Standard children cannot exceed max children",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_INVALID_TOTAL_GUEST_CAPACITY(5205, "Standard total guests cannot exceed max total guests",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_MAX_ADULTS_EXCEED_TOTAL(5206, "Max adults cannot exceed max total guests",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_MAX_CHILDREN_EXCEED_TOTAL(5207, "Max children cannot exceed max total guests",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_PRICE_INVALID(5208, "Base price must be greater than or equal to 0", HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_QUANTITY_INVALID(5209, "Total quantity must be greater than or equal to 0",
                        HttpStatus.BAD_REQUEST),
        DUPLICATE_BED_IN_REQUEST(5210, "Duplicate bed ID found in request", HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_BEDS_NOT_NULL(5211, "Hotel room type beds list must not be null", HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_BEDS_NOT_EMPTY(5212, "Hotel room type beds list must not be empty", HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_HOTEL_ID_NOT_NULL(5213, "Hotel ID for room type configuration must not be null",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_ROOM_TYPE_ID_NOT_NULL(5214, "Room type ID for hotel room type configuration must not be null",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_STANDARD_ADULTS_NOT_NULL(5215, "Standard adults capacity for hotel room type must not be null",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_STANDARD_ADULTS_MIN_ZERO(5216,
                        "Standard adults capacity for hotel room type must be at least 0",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_STANDARD_CHILDREN_NOT_NULL(5217,
                        "Standard children capacity for hotel room type must not be null",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_STANDARD_CHILDREN_MIN_ZERO(5218,
                        "Standard children capacity for hotel room type must be at least 0", HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_MAX_ADULTS_NOT_NULL(5219, "Maximum adults capacity for hotel room type must not be null",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_MAX_ADULTS_MIN_ZERO(5220, "Maximum adults capacity for hotel room type must be at least 0",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_MAX_CHILDREN_NOT_NULL(5221, "Maximum children capacity for hotel room type must not be null",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_MAX_CHILDREN_MIN_ZERO(5222, "Maximum children capacity for hotel room type must be at least 0",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_MAX_INFANTS_NOT_NULL(5223, "Maximum infants capacity for hotel room type must not be null",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_MAX_INFANTS_MIN_ZERO(5224, "Maximum infants capacity for hotel room type must be at least 0",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_MAX_TOTAL_GUESTS_NOT_NULL(5225,
                        "Maximum total guests capacity for hotel room type must not be null", HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_MAX_TOTAL_GUESTS_MIN_ZERO(5226,
                        "Maximum total guests capacity for hotel room type must be at least 0", HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_MAX_EXTRA_BEDS_NOT_NULL(5227,
                        "Maximum extra beds capacity for hotel room type must not be null",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_MAX_EXTRA_BEDS_MIN_ZERO(5228,
                        "Maximum extra beds capacity for hotel room type must be at least 0",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_BASE_PRICE_NOT_NULL(5229, "Hotel room type base price must not be null",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_BASE_PRICE_MIN_ZERO(5230, "Hotel room type base price must be at least 0.0",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_TOTAL_QUANTITY_NOT_NULL(5231, "Hotel room type total quantity must not be null",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_TOTAL_QUANTITY_MIN_ZERO(5232, "Hotel room type total quantity must be at least 0",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_STATUS_NOT_NULL(5233, "Hotel room type status must not be null", HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_BED_ROOM_BED_ID_NOT_NULL(5234,
                        "Room bed ID for hotel room type bed configuration must not be null",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_BED_QUANTITY_NOT_NULL(5235,
                        "Room bed quantity for hotel room type bed configuration must not be null",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_BED_QUANTITY_MIN_ONE(5236,
                        "Room bed quantity for hotel room type bed configuration must be at least 1",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_BED_LIMIT_EXCEEDED(5237,
                        "Total beds configuration (standard + extra) exceeds physical room capacity",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_MAX_BEDS_NOT_NULL(5238,
                        "Maximum physical beds capacity for hotel room type must not be null",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_MAX_BEDS_MIN_ZERO(5239,
                        "Maximum physical beds capacity for hotel room type must be at least 0",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_MAX_EXTRA_BEDS_EXCEED_MAX_BEDS(5242,
                        "Maximum extra beds capacity cannot exceed maximum physical beds capacity",
                        HttpStatus.BAD_REQUEST),
        DUPLICATE_FEATURE_IN_REQUEST(5240, "Duplicate room feature ID found in request", HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_FEATURE_IDS_NOT_NULL(5241, "Room feature IDs list must not be null", HttpStatus.BAD_REQUEST),
        DUPLICATE_CATALOG_ITEM_IN_REQUEST(5250, "Duplicate catalog item ID found in request", HttpStatus.BAD_REQUEST),
        CATALOG_ITEM_HOTEL_MISMATCH(5251, "Catalog item does not belong to the same hotel as the room type",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_CATALOG_ITEMS_NOT_NULL(5252, "Catalog items list must not be null", HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_CATALOG_ITEM_ID_NOT_NULL(5253, "Catalog item ID must not be null", HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_CATALOG_ITEM_USAGE_NOT_NULL(5254, "Catalog item usage must not be null",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_CATALOG_ITEM_PRICE_NOT_NULL(5255, "Catalog item price must not be null",
                        HttpStatus.BAD_REQUEST),
        HOTEL_ROOM_TYPE_CATALOG_ITEM_PRICE_MIN_ZERO(5256, "Catalog item price must be at least 0.0",
                        HttpStatus.BAD_REQUEST),

        ROOM_INSTANCE_NOT_FOUND(5260, "Room instance not found", HttpStatus.NOT_FOUND),
        ROOM_INSTANCE_ALREADY_EXISTS(5261, "Room number already exists in this hotel", HttpStatus.CONFLICT),
        ROOM_INSTANCE_HOTEL_MISMATCH(5262, "The selected room type does not belong to this hotel", HttpStatus.BAD_REQUEST),
        ROOM_INSTANCE_EXCEEDS_TOTAL_QUANTITY(5263, "Cannot create room: maximum total quantity for this room type has been reached", HttpStatus.BAD_REQUEST),
        ROOM_INSTANCE_HOTEL_ID_NOT_NULL(5264, "Hotel ID for room instance must not be null", HttpStatus.BAD_REQUEST),
        ROOM_INSTANCE_ROOM_TYPE_ID_NOT_NULL(5265, "Room type ID for room instance must not be null", HttpStatus.BAD_REQUEST),
        ROOM_INSTANCE_ROOM_NUMBER_NOT_BLANK(5266, "Room number for room instance must not be blank", HttpStatus.BAD_REQUEST),
        ROOM_INSTANCE_STATUS_NOT_NULL(5267, "Current status for room instance must not be null", HttpStatus.BAD_REQUEST),

        VAT_RULE_NOT_FOUND(8001, "Vat rule not found", HttpStatus.NOT_FOUND),
        VAT_RULE_CODE_EXISTED(8002, "Vat rule code already existed", HttpStatus.BAD_REQUEST),
        VAT_RULE_NAME_EXISTED(8003, "Vat rule name already existed", HttpStatus.BAD_REQUEST),
        VAT_RULE_INVALID_DATE_RANGE(8004, "Start date must be before or equal to end date", HttpStatus.BAD_REQUEST),
        VAT_RULE_CODE_NOT_BLANK(8005, "Vat rule code must not be blank", HttpStatus.BAD_REQUEST),
        VAT_RULE_NAME_NOT_BLANK(8006, "Vat rule name must not be blank", HttpStatus.BAD_REQUEST),
        VAT_RULE_PERCENT_NOT_NULL(8007, "Vat rule percent must not be null", HttpStatus.BAD_REQUEST),
        VAT_RULE_APPLIES_TO_NOT_NULL(8008, "Vat rule appliesTo must not be null", HttpStatus.BAD_REQUEST),
        VAT_RULE_CODE_MAX_LENGTH(8009, "Vat rule code must not exceed 50 characters", HttpStatus.BAD_REQUEST),
        VAT_RULE_NAME_MAX_LENGTH(8010, "Vat rule name must not exceed 150 characters", HttpStatus.BAD_REQUEST),
        VAT_RULE_PERCENT_MIN(8011, "Vat rule percent must be at least 0.00", HttpStatus.BAD_REQUEST),
        VAT_RULE_PERCENT_MAX(8012, "Vat rule percent must not exceed 100.00", HttpStatus.BAD_REQUEST),
        VAT_RULE_STATUS_NOT_NULL(8013, "Vat rule status must not be null", HttpStatus.BAD_REQUEST),

        HOLIDAY_NOT_FOUND(8101, "Holiday calendar not found", HttpStatus.NOT_FOUND),
        HOLIDAY_DATE_EXISTED(8102, "A holiday has already been configured for this date", HttpStatus.BAD_REQUEST),
        HOLIDAY_NAME_NOT_BLANK(8103, "Holiday name must not be blank", HttpStatus.BAD_REQUEST),
        HOLIDAY_DATE_NOT_NULL(8104, "Holiday date must not be null", HttpStatus.BAD_REQUEST),
        HOLIDAY_NAME_MAX_LENGTH(8105, "Holiday name must not exceed 150 characters", HttpStatus.BAD_REQUEST),
        HOLIDAY_STATUS_NOT_NULL(8106, "Holiday status must not be null", HttpStatus.BAD_REQUEST),
        HOLIDAY_NAME_EXISTED(8107, "Holiday name already existed", HttpStatus.BAD_REQUEST),

        PRICING_RULE_NOT_FOUND(8200, "Pricing rule not found", HttpStatus.NOT_FOUND),
        PRICING_RULE_INVALID_DATE_RANGE(8201, "Pricing rule start date must be before or equal to end date", HttpStatus.BAD_REQUEST),
        PRICING_RULE_ADJUSTMENT_VALUE_INVALID(8202, "Pricing rule adjustment value must be greater than 0", HttpStatus.BAD_REQUEST),
        PRICING_RULE_HOLIDAY_CALENDAR_REQUIRED(8203, "Holiday calendar ID must not be null when rule type is HOLIDAY", HttpStatus.BAD_REQUEST),
        PRICING_RULE_HOLIDAY_CALENDAR_MUST_BE_NULL(8204, "Holiday calendar ID must be null when rule type is not HOLIDAY", HttpStatus.BAD_REQUEST),
        PRICING_RULE_HOTEL_ROOM_TYPE_ID_NOT_NULL(8205, "Hotel room type ID for pricing rule must not be null", HttpStatus.BAD_REQUEST),
        PRICING_RULE_RULE_TYPE_NOT_NULL(8206, "Pricing rule type must not be null", HttpStatus.BAD_REQUEST),
        PRICING_RULE_ADJUSTMENT_TYPE_NOT_NULL(8207, "Pricing rule adjustment type must not be null", HttpStatus.BAD_REQUEST),
        PRICING_RULE_ADJUSTMENT_VALUE_NOT_NULL(8208, "Pricing rule adjustment value must not be null", HttpStatus.BAD_REQUEST),
        PRICING_RULE_START_DATE_NOT_NULL(8209, "Pricing rule start date must not be null", HttpStatus.BAD_REQUEST),
        PRICING_RULE_END_DATE_NOT_NULL(8210, "Pricing rule end date must not be null", HttpStatus.BAD_REQUEST),
        PRICING_RULE_PRIORITY_NOT_NULL(8211, "Pricing rule priority must not be null", HttpStatus.BAD_REQUEST),
        PRICING_RULE_PRIORITY_MIN(8212, "Pricing rule priority must be at least 0", HttpStatus.BAD_REQUEST),
        PRICING_RULE_STATUS_NOT_NULL(8213, "Pricing rule status must not be null", HttpStatus.BAD_REQUEST),
        PRICING_RULE_HOLIDAY_DATE_OUT_OF_RANGE(8214, "The associated holiday date must fall within the pricing rule start and end dates", HttpStatus.BAD_REQUEST),
        PRICING_RULE_TYPE_NOT_FOUND(8215, "Pricing rule type configuration not found", HttpStatus.NOT_FOUND),
        PRICING_RULE_TYPE_ALREADY_EXISTS(8216, "Pricing rule type configuration with this code already exists", HttpStatus.BAD_REQUEST),

        DISCOUNT_RULE_NOT_FOUND(8300, "Discount rule not found", HttpStatus.NOT_FOUND),
        DISCOUNT_RULE_VALUE_INVALID(8301, "Discount value must be greater than 0", HttpStatus.BAD_REQUEST),
        DISCOUNT_RULE_MIN_NIGHTS_REQUIRED(8302, "Minimum nights must not be null and must be at least 3 when rule type is LONG_STAY", HttpStatus.BAD_REQUEST),
        DISCOUNT_RULE_MIN_NIGHTS_MUST_BE_NULL(8303, "Minimum nights must be null when rule type is not LONG_STAY", HttpStatus.BAD_REQUEST),
        DISCOUNT_RULE_HOTEL_ROOM_TYPE_ID_NOT_NULL(8304, "Hotel room type ID for discount rule must not be null", HttpStatus.BAD_REQUEST),
        DISCOUNT_RULE_RULE_TYPE_NOT_NULL(8305, "Discount rule type must not be null", HttpStatus.BAD_REQUEST),
        DISCOUNT_RULE_DISCOUNT_TYPE_NOT_NULL(8306, "Discount type must not be null", HttpStatus.BAD_REQUEST),
        DISCOUNT_RULE_DISCOUNT_VALUE_NOT_NULL(8307, "Discount value must not be null", HttpStatus.BAD_REQUEST),
        DISCOUNT_RULE_STATUS_NOT_NULL(8308, "Discount rule status must not be null", HttpStatus.BAD_REQUEST),
        DISCOUNT_RULE_INVALID_DATE_RANGE(8309, "Discount rule start date must be before or equal to end date", HttpStatus.BAD_REQUEST),
        DISCOUNT_RULE_OUTSIDE_CAMPAIGN_DATES(8310, "Discount rule dates must fall within the associated campaign dates", HttpStatus.BAD_REQUEST),
        DISCOUNT_RULE_START_DATE_NOT_NULL(8311, "Discount rule start date must not be null", HttpStatus.BAD_REQUEST),
        DISCOUNT_RULE_END_DATE_NOT_NULL(8312, "Discount rule end date must not be null", HttpStatus.BAD_REQUEST),
        DISCOUNT_RULE_OVERLAPPING(8313, "Discount rule dates overlap with an existing rule", HttpStatus.BAD_REQUEST),
        DISCOUNT_RULE_TYPE_NOT_FOUND(8314, "Discount rule type configuration not found", HttpStatus.NOT_FOUND),
        DISCOUNT_RULE_TYPE_ALREADY_EXISTS(8315, "Discount rule type configuration with this code already exists", HttpStatus.BAD_REQUEST),
        DISCOUNT_RULE_DUPLICATE_CONDITIONS(8316, "Duplicate discount conditions found in tiers", HttpStatus.BAD_REQUEST),
        DISCOUNT_RULE_ROOM_TYPES_REQUIRED(8317, "Applied room type IDs must not be empty", HttpStatus.BAD_REQUEST),
        DISCOUNT_RULE_TIERS_REQUIRED(8318, "Discount tiers must not be empty", HttpStatus.BAD_REQUEST),
        DISCOUNT_RULE_TIER_CONDITIONS_NOT_NULL(8319, "Tier conditions must not be null", HttpStatus.BAD_REQUEST),
        DISCOUNT_RULE_DUPLICATE_TIER_CONDITION(8320, "A tier with the exact same condition already exists for this room type during the specified date range", HttpStatus.BAD_REQUEST),

        CAMPAIGN_NOT_FOUND(8400, "Campaign not found", HttpStatus.NOT_FOUND),
        CAMPAIGN_INVALID_DATE_RANGE(8401, "Campaign start date must be before or equal to end date", HttpStatus.BAD_REQUEST),
        CAMPAIGN_HOTEL_ID_NOT_NULL(8402, "Hotel ID for campaign must not be null", HttpStatus.BAD_REQUEST),
        CAMPAIGN_NAME_NOT_BLANK(8403, "Campaign name must not be blank", HttpStatus.BAD_REQUEST),
        CAMPAIGN_START_DATE_NOT_NULL(8404, "Campaign start date must not be null", HttpStatus.BAD_REQUEST),
        CAMPAIGN_END_DATE_NOT_NULL(8405, "Campaign end date must not be null", HttpStatus.BAD_REQUEST),
        CAMPAIGN_STATUS_NOT_NULL(8406, "Campaign status must not be null", HttpStatus.BAD_REQUEST),
        CAMPAIGN_NAME_OVERLAPPING(8407, "A campaign with this name already exists during the specified date range", HttpStatus.BAD_REQUEST),

        SURCHARGE_RULE_NOT_FOUND(8500, "Surcharge rule not found", HttpStatus.NOT_FOUND),
        SURCHARGE_RULE_INVALID_DATE_RANGE(8501, "Surcharge rule start date must be before or equal to end date", HttpStatus.BAD_REQUEST),
        SURCHARGE_RULE_INVALID_AGE_RANGE(8502, "Surcharge rule min age must be less than or equal to max age", HttpStatus.BAD_REQUEST),
        SURCHARGE_RULE_VALUE_INVALID(8503, "Surcharge rule adjustment value must be greater than or equal to 0", HttpStatus.BAD_REQUEST),
        SURCHARGE_RULE_HOTEL_ROOM_TYPE_ID_NOT_NULL(8504, "Hotel room type ID for surcharge rule must not be null", HttpStatus.BAD_REQUEST),
        SURCHARGE_RULE_RULE_TYPE_NOT_NULL(8505, "Surcharge rule type must not be null", HttpStatus.BAD_REQUEST),
        SURCHARGE_RULE_ADJUSTMENT_TYPE_NOT_NULL(8506, "Surcharge rule adjustment type must not be null", HttpStatus.BAD_REQUEST),
        SURCHARGE_RULE_ADJUSTMENT_VALUE_NOT_NULL(8507, "Surcharge rule adjustment value must not be null", HttpStatus.BAD_REQUEST),
        SURCHARGE_RULE_START_DATE_NOT_NULL(8508, "Surcharge rule start date must not be null", HttpStatus.BAD_REQUEST),
        SURCHARGE_RULE_END_DATE_NOT_NULL(8509, "Surcharge rule end date must not be null", HttpStatus.BAD_REQUEST),
        SURCHARGE_RULE_STATUS_NOT_NULL(8510, "Surcharge rule status must not be null", HttpStatus.BAD_REQUEST),
        SURCHARGE_RULE_OVERLAP(8511, "Surcharge rule dates overlap with an existing rule", HttpStatus.BAD_REQUEST),

        PRICING_RULE_OVERLAPPING(8600, "Pricing rule dates overlap with an existing rule", HttpStatus.BAD_REQUEST),
        
        AGE_POLICY_NOT_FOUND(8700, "Hotel age policy not found", HttpStatus.NOT_FOUND),
        AGE_POLICY_DUPLICATE_GUEST_TYPE(8701, "This hotel already has an age policy for this guest type", HttpStatus.BAD_REQUEST),
        AGE_POLICY_INVALID_AGE_RANGE(8702, "Min age must be less than or equal to max age", HttpStatus.BAD_REQUEST),
        
        TAX_CATEGORY_NOT_FOUND(8800, "Tax category not found", HttpStatus.NOT_FOUND),
        TAX_CATEGORY_CODE_EXISTED(8801, "Tax category code already exists", HttpStatus.BAD_REQUEST),
        
        ROOM_NOT_FOUND(5262, "Room not found", HttpStatus.NOT_FOUND),
        ROOM_HAS_BOOKING_CONFLICT(5263, "Room has booking conflict", HttpStatus.BAD_REQUEST),
        ROOM_CAPACITY_EXCEEDED(5257, "Requested guest count exceeds maximum capacity allowed for this room type", HttpStatus.BAD_REQUEST),
        INVALID_DATE_RANGE(8501, "Check-in date must be in the future and check-out must be after check-in", HttpStatus.BAD_REQUEST),
        SEARCH_INVALID_ROOM_OCCUPANCY_CONFIGURATION(8512, "Số lượng phòng không khớp với cấu hình số lượng khách", HttpStatus.BAD_REQUEST),
        PRICING_CALCULATION_FAILED(8513, "Pricing calculation failed due to an internal error", HttpStatus.INTERNAL_SERVER_ERROR),
        PRICING_ROOMS_NOT_EMPTY(8514, "Danh sách phòng yêu cầu không được để trống", HttpStatus.BAD_REQUEST),


        ROOM_AVAILABILITY_NOT_FOUND(9001, "No room availability data found for the selected dates", HttpStatus.NOT_FOUND),
        ROOM_NOT_ENOUGH_QUANTITY(9002, "Not enough rooms available for the requested dates", HttpStatus.BAD_REQUEST),
        ROOM_CONCURRENCY_CONFLICT(9003, "The room was just booked by another user. Please try again.", HttpStatus.CONFLICT),
        ROOM_ADULT_CAPACITY_EXCEEDED(9004, "Số lượng người lớn vượt quá quy định", HttpStatus.BAD_REQUEST),
        ROOM_CHILD_CAPACITY_EXCEEDED(9005, "Số lượng trẻ em vượt quá quy định", HttpStatus.BAD_REQUEST),
        ROOM_INFANT_CAPACITY_EXCEEDED(9006, "Số lượng em bé vượt quá quy định", HttpStatus.BAD_REQUEST),

        BOOKING_NOT_FOUND(9100, "Booking not found", HttpStatus.NOT_FOUND),
        ROOM_ALREADY_BLOCKED(9101, "Phòng vừa được người khác chọn, vui lòng chọn phòng khác", HttpStatus.BAD_REQUEST),
        ROOM_NOT_BLOCKED(9102, "Phòng chưa được giữ chỗ (BLOCKED), không thể xác nhận", HttpStatus.BAD_REQUEST),
        INVALID_ROOM_STATUS(9103, "Trạng thái phòng không hợp lệ để xác nhận", HttpStatus.BAD_REQUEST),
        ROOM_QUANTITY_EXCEEDED(9104, "Bạn đã chọn đủ số lượng phòng của đơn này", HttpStatus.BAD_REQUEST),
        ROOM_TYPE_MISMATCH(9105, "Phòng được chọn không khớp với loại phòng đã đặt", HttpStatus.BAD_REQUEST),
        ROOM_ALREADY_CONFIRMED(9106, "Phòng đã được chốt cứng, không thể thay đổi", HttpStatus.BAD_REQUEST),
        INVALID_BOOKING_STATUS(9107, "Trạng thái booking không phải confirm", HttpStatus.BAD_REQUEST),
        BOOKING_DETAIL_NOT_FOUND(9108, "Booking chi tiết không tồn tại", HttpStatus.NOT_FOUND),
        INVOICE_NOT_FOUND(9109, "Hoá đơn không tồn tại", HttpStatus.NOT_FOUND),
        ROOM_NOT_FULLY_ASSIGNED(9110, "Số lượng phòng chưa được gán đủ", HttpStatus.BAD_REQUEST),
        ROOM_GUEST_DECLARATION_NOT_EMPTY(9111, "Danh sách khai báo phòng không được để trống", HttpStatus.BAD_REQUEST),
        GUEST_INFO_NOT_EMPTY(9112, "Phải có ít nhất 1 khách lưu trú trong phòng", HttpStatus.BAD_REQUEST),
        GUEST_FULL_NAME_NOT_BLANK(9113, "Tên khách không được để trống", HttpStatus.BAD_REQUEST),

        MISSING_GUEST_DECLARATION(9114, "Vui lòng khai báo đầy đủ danh sách khách lưu trú thực tế (Tên, CMND/Passport) cho từng phòng.", HttpStatus.BAD_REQUEST),
        GUEST_COUNT_EXCEEDED(9115, "Số lượng khách lưu trú vượt quá giới hạn đã thanh toán. Vui lòng thêm phụ phí người thứ 3 (Extra Person) trước khi Check-in.", HttpStatus.BAD_REQUEST),
        GUEST_TYPE_MISMATCH(9116, "Thành phần người lớn/trẻ em không khớp với thông tin đã đặt. Vui lòng kiểm tra lại hoặc thêm phụ thu chênh lệch độ tuổi.", HttpStatus.BAD_REQUEST),

        ADULT_MISSING_IDENTITY(9117, "Khách người lớn bắt buộc phải cung cấp Loại giấy tờ và Số giấy tờ tùy thân để khai báo lưu trú.", HttpStatus.BAD_REQUEST),

        OOM_INSTANCE_ID_NOT_NULL(9201, "Room instance ID must not be null", HttpStatus.BAD_REQUEST),
        ORDER_ITEM_NOT_EMPTY(9202, "Order items list must not be empty", HttpStatus.BAD_REQUEST),
        CATALOG_ITEM_ID_NOT_NULL(9203, "Catalog item ID must not be null", HttpStatus.BAD_REQUEST),
        MIN_ORDER_ITEM_QUANTITY(9204, "Order item quantity must be at least 1", HttpStatus.BAD_REQUEST),
        BOOKING_UNPAID_BALANCE(9205, "Khách hàng chưa thanh toán chi phí phát sinh trong thời gian lưu trú", HttpStatus.BAD_REQUEST),
        ROOM_MUST_BE_CLEANED_FIRST(9206, "Phòng chưa được dọn dẹp", HttpStatus.BAD_REQUEST),
        ROOM_MAINTENANCE_MUST_CLEAN(9207, "Phòng vừa được bảo trì hoàn tất, chưa được dọn dẹp", HttpStatus.BAD_REQUEST),
        ROOM_SLOT_NOT_AVAILABLE(9208,  "Không tìm thấy dữ liệu slot cho phòng đã chọn trong thời gian lưu trú.", HttpStatus.BAD_REQUEST),
        ROOM_ALREADY_TAKEN(9209, "Phòng này đã bị người khác đặt hoặc đang trong trạng thái không sẵn sàng.", HttpStatus.CONFLICT),
        INSUFFICIENT_PAYMENT(9210, "Số tiền thanh toán chưa đủ", HttpStatus.BAD_REQUEST),

        // Lỗi liên quan đến Tồn kho (Availability)
        OUT_OF_INVENTORY(9210, "Hạng phòng này đã hết số lượng phòng trống cho các ngày bạn đã chọn.", HttpStatus.CONFLICT),
        INVALID_WALKIN_DATE(9211, "Ngày walk-in đang ở tuong lai, không hợp lệ", HttpStatus.BAD_REQUEST),
        ;

        ErrorCode(int code, String message, HttpStatusCode statusCode) {
                this.code = code;
                this.message = message;
                this.statusCode = statusCode;
        }

        private int code;
        private String message;
        private HttpStatusCode statusCode;
}
